### ISSUE TITLE
NullPointer Exception

### ISSUE THREAD

**Issue by themadhatterz** [CheckPoint-APIs-Team/ShowPolicyPackage#3]
Getting a NullPointer exception at the following line I think.

https://github.com/CheckPoint-APIs-Team/ShowPolicyPackage/blob/c32442943408b95bdb64d19d42de4aa0e015e3f3/src/main/java/com/checkpoint/mgmt_api/examples/ShowPackageTool.java#L1203

Running the following:
{Expert]# ./web_api_show_package.sh -v
Exception in thread "main" java.lang.NullPointerException
        at com.checkpoint.mgmt_api.examples.ShowPackageTool.setGatewayAndServerPolicy(ShowPackageTool.java:1213)
        at com.checkpoint.mgmt_api.examples.ShowPackageTool.buildNewGatewayOrServer(ShowPackageTool.java:1185)
        at com.checkpoint.mgmt_api.examples.ShowPackageTool.collectGatewaysInUseAndInstalledPolicies(ShowPackageTool.java:244)
        at com.checkpoint.mgmt_api.examples.ShowPackageTool.main(ShowPackageTool.java:158)

**Comment by CheckPoint-APIs-Team** [comment]
Hi,
The code here is working.
You are probably using the default JAVA executable file on CheckPoint management server.
Recompile this source code and replace the JAR on the server by following the instructions section.
Thanks for your input.

**Comment by themadhatterz** [comment]
The script works on several devices, and I've moved a jar from a working device to the affected one. I can recompile from the repository, but I have my doubts.

**Comment by CheckPoint-APIs-Team** [comment]
This null pointer exception is a known issue on R80.10 servers. The fix will be deliverd on a next HF.
The source code on this repo already has the fix.

**Comment by themadhatterz** [comment]
Thank you for the detailed follow up.
